{% set name = "click-loglevel" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d582e62c373c43d98759942d07647a9299c50c5c290d6b0ac3a17ed1ecbb6eba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - click >=8

test:
  requires:
    - anyio
    - asyncclick
    - pytest
    - pytest-cov
    - python {{ python_min }}
    - trio
  source_files:
    - test
    - tox.ini
  imports:
    - click_loglevel
  commands:
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/click-loglevel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Log level parameter type for Click
  description: |
    `click-loglevel` provides a `LogLevel` parameter type for use in Click
    programs that wish to let the user set the logging level.  It accepts all
    of the `logging` log level names (`CRITICAL`, `ERROR`, `WARNING`, `INFO`,
    `DEBUG`, and `NOTSET`, all case insensitive), and converts them into their
    corresponding numeric values.  It also accepts integer values and leaves
    them as-is.  Custom log levels are also supported.
  dev_url: https://github.com/jwodder/click-loglevel

extra:
  recipe-maintainers:
    - jwodder
